Repository forcutbook/forcutbook, pull requests merged in 2024-08, with the labels that each got.

#20 친구 요청, 수락, 수락 대기 목록 조회 기능 개발
  server/forcutbook/build.gradle
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/Diary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/DiaryImage.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/UserDiary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/domain/Friend.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendAcceptListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendAcceptResDto.java
  server/forcutbook/src/main/java/konkuk/global/domain/Status.java
  server/forcutbook/src/main/java/konkuk/global/domain/TimeEntity.java
  server/forcutbook/src/main/java/konkuk/global/dto/SuccessResDto.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
Labels: 기능 개발

#22 feat : 팔로워, 팔로잉 목록 조회
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendAcceptListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendAcceptResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendResDto.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
Labels: 기능 개발

#25 feat : 다이어리 조회에 관한 기능 개발
  server/forcutbook/build.gradle
  server/forcutbook/src/main/java/konkuk/forcutbook/ForcutbookApplication.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/Diary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/UserDiary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryAddDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryDetailResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryFeedListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryFeedResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryListEachResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiarySimpleResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustom.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImpl.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/DiaryServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImplTest.java
Labels: 기능 개발

#27 feat : 다이어리 조회 오류 개선 및 친구 요청 거절, 특정 다이어리 수정 기능 개발
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/Diary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryUpdateDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImpl.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/domain/Friend.java
  server/forcutbook/src/main/resources/application.yml
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/DiaryServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImplTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
Labels: 기능 개발

#30 Feat: social Login
  server/forcutbook/build.gradle
  server/forcutbook/src/main/java/konkuk/forcutbook/global/config/SecurityConfig.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/exception/BaseException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/exception/errorcode/BaseExceptionErrorcode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/exception/handler/BaseExceptionHandler.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/exception/OAuthException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/exception/errorcode/OAuthExceptionErrorCode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/exception/handler/OAuthExceptionHandler.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/service/CustomOAuth2UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/service/OAuth2UserPrincipal.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/KakaoOAuth2UserInfo.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/KakaoOAuth2UserUnlink.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/OAuth2UserInfo.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/util/CookieUtils.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseErrorResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/ResponseStatus.java
  server/forcutbook/src/main/resources/application.yml
Labels: 기능 개발

#32 Fix: delete kakao social login
  server/forcutbook/build.gradle
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/User.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/dto/GetUserListDTO.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/config/SecurityConfig.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/service/CustomOAuth2UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/service/OAuth2UserPrincipal.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/KakaoOAuth2UserInfo.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/KakaoOAuth2UserUnlink.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/oauth/user/OAuth2UserInfo.java
Labels: 버그 수정

#34 refactor : DiaryService, FriendService Exception 개선
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/Diary.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/domain/DiaryImage.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryAddDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/exception/DiaryException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/exception/errorcode/DiaryExceptionErrorCode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImpl.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/domain/Friend.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/exception/FriendException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/exception/errorcode/FriendExceptionErrorCode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/domain/Status.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/domain/TimeEntity.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/exception/handler/BaseExceptionHandler.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseResultDto.java
  server/forcutbook/src/main/java/konkuk/global/dto/SuccessResDto.java
  server/forcutbook/src/main/resources/application.yml
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/DiaryServiceIntegrationTest.java
Labels: 리팩터링

#35 Refact: BaseResponse 적용
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/api/ApiLoginResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/api/ApiLogoutResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/api/ApiSignupResponse.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/exception/UserException.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/exception/errorcode/UserExceptionErrorcode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/exception/handler/UserExceptionHandler.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseResponse.java
  server/forcutbook/src/main/resources/application.yml
Labels: 리팩터링

#37 Feat: get user detail info
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/dto/GetUserInfoDTO.java
Labels: 기능 개발

#38 feat : 다이어리 목록 조회에서 팔로잉, 팔로워, 다이어리 작성 수 제거
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryDetailResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryFeedResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImpl.java
Labels: 기능 개발, 리팩터링

#40 test : 다이어리 조회 필드 변경에 따른 테스트 수정
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/DiaryServiceIntegrationTest.java
Labels: 리팩터링

#41 Feat: 유저 상세 조회에 구독중, 요청중, 구독 상태 추가
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/UserService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/dto/GetUserInfoDTO.java
  server/forcutbook/src/main/java/konkuk/forcutbook/domain/user/exception/errorcode/UserExceptionErrorcode.java
Labels: 기능 개발

#43 feat : 친구 요청 취소 개발
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/exception/errorcode/FriendExceptionErrorCode.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
Labels: 기능 개발

#45 Feature/44
  server/forcutbook/src/main/java/konkuk/forcutbook/api/huggingface/FileConversion.java
  server/forcutbook/src/main/java/konkuk/forcutbook/api/huggingface/HuggingFaceResultDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/api/huggingface/ImageToTextApiProvider.java
  server/forcutbook/src/main/java/konkuk/forcutbook/api/s3/S3ServiceProvider.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/DiaryService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/exception/errorcode/DiaryExceptionErrorCode.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendResultDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendStatus.java
  server/forcutbook/src/main/java/konkuk/forcutbook/global/response/BaseResponse.java
  server/forcutbook/src/main/resources/application.yml
  server/forcutbook/src/test/java/konkuk/forcutbook/api/ImageToTextApiProviderTest.java
Labels: 기능 개발

#48 feat : 팔로워 삭제 기능 개발 및 테스트 작성
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
Labels: 기능 개발

#49 feat : 팔로잉, 팔로워 기능 수정
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/dto/DiaryListEachResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/diary/repository/DiaryRepositoryCustomImpl.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendCustomRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendRepository.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FollowListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FollowResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FriendStatus.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/exception/FriendCustomRepositoryImpl.java
  server/forcutbook/src/test/java/konkuk/forcutbook/diary/DiaryServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/exception/FriendCustomRepositoryImplTest.java
Labels: 기능 개발

#50 fix : server브랜치와의 충돌 오류 수정
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/exception/FriendCustomRepositoryImplTest.java
Labels: 버그 수정

#51 feat : 팔로잉 조회 경로 수정
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendController.java
Labels: 기능 개발

#52 feat : 팔로잉 팔로워 조회에 사용자 정보 필드 추가
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/FriendService.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FollowListResDto.java
  server/forcutbook/src/main/java/konkuk/forcutbook/friend/dto/FollowResDto.java
Labels: 기능 개발

#53 fix : 팔로잉 팔로워 조회 dto변경으로 인한 테스트 오류 수정
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/exception/FriendCustomRepositoryImplTest.java
Labels: 버그 수정

#54 fix : 팔로잉 팔로워 조회 dto변경으로 인한 테스트 오류 수정
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/FriendServiceIntegrationTest.java
  server/forcutbook/src/test/java/konkuk/forcutbook/friend/exception/FriendCustomRepositoryImplTest.java
Labels: 버그 수정
